[modules]
autoload=yes

; deprecated / conflicting
noload => chan_sip.so
noload => chan_unistim.so

; HEP (packet capture) - not used
noload => res_hep.so
noload => res_hep_pjsip.so
noload => res_hep_rtcp.so

; CDR/CEL backends - no database present in the container
noload => cdr_pgsql.so
noload => cdr_radius.so
noload => cdr_sqlite3_custom.so
noload => cdr_tds.so
noload => cel_radius.so
noload => cel_sqlite3_custom.so
noload => cel_tds.so

; voicemail backends
noload => app_voicemail_imap.so
noload => app_voicemail_odbc.so

; misc
noload => pbx_dundi.so
